### ISSUE TITLE
Error 500 when uploading custom icons

### ISSUE THREAD

**Issue by rcarmo** [linuxserver/docker-heimdall#16]
I'm using the ARM 32 image, and am getting a 500 error whenever I try to upload a custom icon. 

Permissions on the config volume match the UID/GID set, and there are no logs whatsoever.

The Host OS is Ubuntu 16.04 on `armhf`, I'm using `docker-compose` to start it:

```yaml
services:
  heimdall:
    image: "lsioarmhf/heimdall"
    container_name: heimdall
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ${HOME}/.heimdall/config:/config
      - ${HOME}/.heimdall/data:/data
    ports:
      - "8080:80"
      - "8443:443"
```

And the logs read:

```
$ vi ~/Services/docker-compose.yml 
rcarmo@home:~/.heimdall$ docker logs heimdall
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
[cont-init.d] 50-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

Again, there are no error messages.
