### ISSUE TITLE
permissions on /var/lib/nginx/tmp

### ISSUE THREAD

**Issue by rcarmo** [linuxserver/docker-heimdall#68]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

While trying to create a new tag and upload an image for it, I got a 500 error and this shows up in `log/nginx/error.log`:

```
2020/10/25 15:52:35 [crit] 361#361: *4 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied), client: 192.168.1.125, server: _, request: "POST /tags HTTP/1.1", host: "home.lan", referrer: "http://home.lan/tags/create"
```

------------------------------

## Current Behavior

See above

## Environment
**OS:** Ubuntu
**CPU architecture:** arm32v7
**How docker service was installed:**

Official Docker binaries

## Command used to create docker container (run/create/compose/screenshot)

Compose file:

```
services:
  heimdall:
    image: "linuxserver/heimdall"
    hostname: heimdall
    container_name: heimdall
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /tmp/heimdall:/var/tmp/nginx
      - ${HOME}/.config/heimdall:/config
    ports:
      - "${PRIMARY_IP}:80:80"
      - "${PRIMARY_IP}:443:443"
```

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
New container detected, installing Heimdall
Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
