### ISSUE TITLE
Failure to start when config stored in NFS

### ISSUE THREAD

**Issue by adamus1red** [linuxserver/docker-heimdall#81]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Heimdall operates normally

## Current Behavior
Fails to start. Issue appears to be the chown in `/etc/cont-init.d/50-config`

## Steps to Reproduce

1. `/config` be bound mount to an NFS share. i.e. /net/docker/heimdall
2. `docker-compose up`

## Environment
**OS:** debian
**CPU architecture:** x86_64 & arm64
**How docker service was installed:**
Installed from official docker repos.

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "3.8"
services:
  heimdall:
    image: registry.national-defence.network/lscr.io/linuxserver/heimdall
    environment:
      - PUID=1000015
      - PGID=1000019
      - TZ=Europe/London
    volumes:
      - /net/docker/heimdall/config:/config
    ports:
      - 80
      - 443
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000015
User gid:    1000019
-------------------------------------

chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
chown: changing ownership of '/config/nginx/site-confs/default': Operation not permitted
.... many many lines ....
chmod: changing permissions of '/config/www/SupportedApps/Droppy/droppy.png': Operation not permitted
chmod: changing permissions of '/config/www/app.sqlite': Operation not permitted
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
New container detected, installing Heimdall
Setting permissions
chown: changing ownership of '/config/nginx/site-confs/default': Operation not permitted
.... many many lines ....
chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 50-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
