### ISSUE TITLE
deluge API blows up DNS queries for the same domain

### ISSUE THREAD

**Issue by master-hax** [linuxserver/docker-heimdall#85]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

using a hostname for the deluge enhanced app functionality spams repeated DNS requests
------------------------------

## Expected Behavior

heimdall should make a DNS query for any FQDN, then cache it for 60 seconds per the TTL before making another DNS request

## Current Behavior

heimdall queries the DNS server seemingly once for every API call, leading to more than 1000 requests for the same domain per minute

## Steps to Reproduce

1. start [Heimdall](https://hub.docker.com/r/linuxserver/deluge)
2. start [Deluge](https://hub.docker.com/r/linuxserver/deluge), point a DNS name at Deluge
4. use Heimdall Deluge enhanced app functionality using Deluge's domain name, which seems to function as expected however makes a DNS request for every API call. which is quite a lot given the frequency at which the deluge API refreshes.

same behavior can be seen in the Portainer functionality, but not as wild in volume. note that the issue does NOT occur when I override the Deluge API URL to use an IP address instead of a hostname.

## Environment
**OS:** DietPi
**CPU architecture:** arm64
**How docker service was installed:**

dunno

## Command used to create docker container (run/create/compose/screenshot)

```
  start-page:
    image: lscr.io/linuxserver/heimdall
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - PUID=xxxx
      - PGID=xxxxx
    volumes:
      - heimdall-data-volume:/config # NFS share
    ports:
      - 80:80
```
## Docker logs

```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
New container detected, installing Heimdall
Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
