### ISSUE TITLE
High CPU usage since a few days

### ISSUE THREAD

**Issue by Nebucatnetzer** [linuxserver/docker-heimdall#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
The CPU usuage for Heimdall was always quite low but since a few days it increase quite dramatically for me.
CPU usuage of less than 1% in idle.

## Current Behavior

![image](https://user-images.githubusercontent.com/2287221/156884167-5e64dbff-f816-4ad0-b5f9-d27512e93aef.png)

Down and Up again didn't help and there is no newer image.

## Steps to Reproduce

1. Start the service
2. Look at the CPU usuage
3. `php-fpm: pool www` kicks in every few secconds

## Environment
**OS:** Proxmox 6.3
**CPU architecture:** x86_64
**How docker service was installed:**
Distro Repo (Docker version 20.10.9, build v20.10.9)

## Command used to create docker container (run/create/compose/screenshot)

```
version: "2"
services:
  traefik:
    image: "traefik:v2.2"
    ports:
      - "443:443"
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Zurich
    volumes:
      - ./config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`example.com`)"
      - "traefik.http.routers.heimdall.entrypoints=websecure"
      - "traefik.http.routers.heimdall.tls.certresolver=myresolver"
      - "traefik.http.routers.heimdall.middlewares=default-headers@file"
    restart: unless-stopped
```

## Docker logs

Attaching to heimdall_traefik_1, heimdall
heimdall    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
heimdall    | [s6-init] ensuring user provided files have correct perms...exited 0.
heimdall    | [fix-attrs.d] applying ownership & permissions fixes...
heimdall    | [fix-attrs.d] done.
heimdall    | [cont-init.d] executing container initialization scripts...
heimdall    | [cont-init.d] 01-envfile: executing... 
heimdall    | [cont-init.d] 01-envfile: exited 0.
heimdall    | [cont-init.d] 02-tamper-check: executing... 
heimdall    | [cont-init.d] 02-tamper-check: exited 0.
heimdall    | [cont-init.d] 10-adduser: executing... 
heimdall    | -------------------------------------
heimdall    |           _         ()
heimdall    |          | |  ___   _    __
heimdall    |          | | / __| | |  /  \ 
heimdall    |          | | \__ \ | | | () |
heimdall    |          |_| |___/ |_|  \__/
heimdall    | Brought to you by linuxserver.io
heimdall    | -------------------------------------
heimdall    | To support LSIO projects visit:
heimdall    | https://www.linuxserver.io/donate/
heimdall    | -------------------------------------
heimdall    | GID/UID
heimdall    | -------------------------------------
heimdall    | User uid:    1001
heimdall    | User gid:    1001
heimdall    | -------------------------------------
heimdall    | [cont-init.d] 10-adduser: exited 0.
heimdall    | [cont-init.d] 20-config: executing... 
heimdall    | [cont-init.d] 20-config: exited 0.
heimdall    | [cont-init.d] 30-keygen: executing... 
heimdall    | using keys found in /config/keys
heimdall    | [cont-init.d] 30-keygen: exited 0.
heimdall    | [cont-init.d] 50-config: executing... 
heimdall    | New container detected, installing Heimdall
heimdall    | Setting permissions
heimdall    | [cont-init.d] 50-config: exited 0.
heimdall    | [cont-init.d] 90-custom-folders: executing... 
heimdall    | [cont-init.d] 90-custom-folders: exited 0.
heimdall    | [cont-init.d] 99-custom-files: executing... 
heimdall    | [custom-init] no custom files found exiting...
heimdall    | [cont-init.d] 99-custom-files: exited 0.
heimdall    | [cont-init.d] done.
heimdall    | [services.d] starting services
heimdall    | [services.d] done.
traefik_1   | time="2022-03-01T09:37:08Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yaml"
